 #  <span style="font-family: 'Verdana '; color: blue  ">  Introduction To Numpy </span> 

In [44]:
#import numpy package 

import numpy as np

In [5]:
# 1D array 
my_arr = [44,43,32,34,54,46,87,89,64,54,23,22,35,12,21,32,45]


**print the array** 

In [7]:
my_arr

[44, 43, 32, 34, 54, 46, 87, 89, 64, 54, 23, 22, 35, 12, 21, 32, 45]

**Now convert the array to numpy array**

In [8]:
# by simply writing np.array() funcion it converts the simple array to numpy array 

np.array(my_arr)

array([44, 43, 32, 34, 54, 46, 87, 89, 64, 54, 23, 22, 35, 12, 21, 32, 45])

In [14]:
# similarlt for 2D array

my_2D_arr = [[23,43], [ 55,54] , [ 43,22] ,[ 56,67] ]
my_2D_arr

[[23, 43], [55, 54], [43, 22], [56, 67]]

In [15]:
np.array(my_2D_arr)

array([[23, 43],
       [55, 54],
       [43, 22],
       [56, 67]])

 ## <span style="font-family: 'Verdana '; color: blue  ">  Generate NumPy Arrays using  Built in methods </span>


###### Generating numpy array using `arange() ` funcion

In [18]:
# printing values from 0 to n-1 that is 9 

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
np.arange(0,10,2)
# basicaly the three parameters stands for, start, end, step value 
# so in this example it starts from 0 to 10 and the step value is 2 

array([0, 2, 4, 6, 8])

 ###### Generating numpy array using `linspace()`funcion.
 
` linspace()` function is a very useful function for generating evenly spaced numbers in NumPy

In [24]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

###### Generating numpy arrays using `zeros()` funcion.

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3,4))

# Generats 3,4  2D arrays of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###### Generating numpy arrays using `ones()` function

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
#similarly it applies for the case of np.zeros()
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###### Generating random  numpy array numbers using `random.rand()` funcion.

The  `np.random.rand()` function is a very useful function for generating random numbers in NumPy.

It can be used for a variety of tasks, such as generating data for machine learning, generating test data, and generating random numbers for games

In [31]:
np.random.rand(4,5)

array([[0.04720396, 0.98945477, 0.2414157 , 0.04714368, 0.24627191],
       [0.65035133, 0.80198036, 0.90017218, 0.48005046, 0.88213802],
       [0.0051294 , 0.87392383, 0.01138353, 0.54723231, 0.05398483],
       [0.63585157, 0.85118698, 0.60433857, 0.30035404, 0.278069  ]])

In [32]:
# 1D array of a rondom numbers
np.random.rand(5)

array([0.58249421, 0.47681602, 0.1555178 , 0.66810265, 0.12172902])

**Generating numpy array using `random.randn()` funcion**.

`np.random.randn()` is a function in the NumPy library that returns a sample (or samples) from the “standard normal” distribution. 

A single float randomly sampled from the distribution is returned if no argument is provided1.

In [33]:
np.random.randn(5)

array([-1.12562827, -0.13054526, -0.82705779, -1.54230146,  2.73838714])

**`np.random.rand()` vs `np.random.randn()`**     

The `np.random.rand()` function generates random numbers that are equally likely to be any value between 0 and 1,

while the `np.random.randn()` function generates random numbers that are more likely to be near 0 than they are to be near 1.

**Generating numpy array using `np.random.randint()` funcion**.

In [41]:
# The np.random.randint(1, 20, 10) function in NumPy generates 10 random integers between 1 and 20, inclusive. 
# The output is a 1D array of 10 random integers.

np.random.randint(1,20,10)

array([ 1, 19, 19, 16, 16,  5,  8,  9,  3, 17])

#  <span style="font-family: 'Arial '; color: Green  "> Summary of  the Built in methods  </span> 

The different methods to generate random NumPy arrays are:

`arange()` = returns values from the specified range.

`linspace()` = returns evenly spaced numbers from the given range.

`ones()` = returns an array of ones.

`zeroes()` = returns an array of zeroes.
 
`eye()` = returns identity matrix.

`random.rand()` = returns an array of random values.

`random.randn()` = returns an array of normalized values.

`random.randint()` = returns an array of integers from a given range.

##  <span style="font-family: 'Verdana '; color: blue  "> Mathematic funcions in Numpy arrays </span> 

In [47]:
array_ = np.random.randint(0,100,20)
array_
# This array generates a 1D array of 20 random integers between 0 and 100, inclusive.

array([97, 90, 32, 44, 29, 80, 17, 14, 84, 28, 59, 85, 45, 21, 66, 24, 89,
       78, 28,  0])

In [48]:
array_.shape

(20,)

As you can see, the output of `array_.shape` is a tuple of two numbers, where the first number is 20 and the second number is 0. 

This means that the array has **20 rows** and **0 columns**.

In [55]:
array_.reshape(5,4)

array([[97, 90, 32, 44],
       [29, 80, 17, 14],
       [84, 28, 59, 85],
       [45, 21, 66, 24],
       [89, 78, 28,  0]])

In [57]:
array_.reshape(11,3)

ValueError: cannot reshape array of size 20 into shape (11,3)

 as you can see above you can not reshape array of size 20 int to `shape(11,3)`.
 
The total size of the new array must be the same as the size of the original array. 

In this case, the size of the new array would be **11*3 = 33**, which is not equal to the size of the original `array (20)`.

Here are some possible shapes that you could reshape the array of size 20 into:

* (4, 5)
* (5, 4)
* (2, 10)
* (10, 2)

In [58]:
array_.reshape(10,2)

array([[97, 90],
       [32, 44],
       [29, 80],
       [17, 14],
       [84, 28],
       [59, 85],
       [45, 21],
       [66, 24],
       [89, 78],
       [28,  0]])

In [65]:
# if you want to transpose the array you simply add .T function  

# T stands for transpose of the matrix

array_.reshape(10,2).T
    

array([[97, 32, 29, 17, 84, 59, 45, 66, 89, 28],
       [90, 44, 80, 14, 28, 85, 21, 24, 78,  0]])

#### Multiplication 

In [68]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#multiplay
array * array

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
array * array * array 

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

#### Division

In [78]:
array / array

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
array / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In Python, the `//` operator performs floor division.

This means that the result of the division is rounded down to the nearest integer. 

For example, `5 // 2` would return **2**, because `5 / 2` is **2.5**, and rounding down to the nearest integer gives us 2.

In [80]:
array // 2

array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int32)

#### Subtraction

In [81]:
array-4

array([-3, -2, -1,  0,  1,  2,  3,  4,  5])

#### Power of an array in NumPy


The `** ` operator is used to raise an array to a power in NumPy. 

The syntax for using the `**` operator is as follows:

`array ** power`

In [82]:
array**4

array([   1,   16,   81,  256,  625, 1296, 2401, 4096, 6561], dtype=int32)

In [85]:
arr = np.arange(1,10)

In [87]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [92]:
np.max(arr)

9

In [94]:
np.min(arr)

1

In [102]:
arr_= np.random.randint(1,100,30)
arr_

array([27, 64, 75, 55, 46, 41, 60, 30, 79, 46, 53, 86, 68, 74, 85, 74, 14,
       62, 43, 26, 57, 76, 58, 80, 42, 78, 45, 66,  6, 16])

In [103]:
np.max(arr_)

86

In [104]:
np.min(arr_)

6

The `np.argmax(arr_)` and `np.argmin(arr_)` functions in NumPy are used to find the index of the maximum and minimum element in an array, respectively.

In [108]:
np.argmax(arr_)

# index of the maximum number 
# meaning our max num which is 86 in this examples is presented in the index 11 of the array 

11

In [110]:
np.argmin(arr_)
# index of the min num 

28

The `np.log(arr_)` function in NumPy takes an array as input and returns a new array with the natural logarithm of each element

In [113]:
np.log(arr_)

array([3.29583687, 4.15888308, 4.31748811, 4.00733319, 3.8286414 ,
       3.71357207, 4.09434456, 3.40119738, 4.36944785, 3.8286414 ,
       3.97029191, 4.4543473 , 4.21950771, 4.30406509, 4.44265126,
       4.30406509, 2.63905733, 4.12713439, 3.76120012, 3.25809654,
       4.04305127, 4.33073334, 4.06044301, 4.38202663, 3.73766962,
       4.35670883, 3.80666249, 4.18965474, 1.79175947, 2.77258872])

In [119]:
np.sin(arr_)
# sin value of each element in the array 

array([ 0.95637593,  0.92002604, -0.38778164, -0.99975517,  0.90178835,
       -0.15862267, -0.30481062, -0.98803162, -0.44411267,  0.90178835,
        0.39592515, -0.92345845, -0.89792768, -0.98514626, -0.17607562,
       -0.98514626,  0.99060736, -0.7391807 , -0.83177474,  0.76255845,
        0.43616476,  0.56610764,  0.99287265, -0.99388865, -0.91652155,
        0.51397846,  0.85090352, -0.02655115, -0.2794155 , -0.28790332])

In [120]:
np.tan(arr_)
# tan value of each element in the array 

array([-3.27370380e+00,  2.34786031e+00, -4.20700951e-01, -4.51830879e+01,
       -2.08661353e+00,  1.60656699e-01,  3.20040389e-01, -6.40533120e+00,
        4.95677533e-01, -2.08661353e+00, -4.31158197e-01,  2.40672971e+00,
       -2.04008160e+00, -5.73702254e+00,  1.78870172e-01, -5.73702254e+00,
        7.24460662e+00, -1.09750978e+00, -1.49838734e+00,  1.17875355e+00,
        4.84699227e-01,  6.86747689e-01,  8.33085685e+00,  9.00365495e+00,
        2.29138799e+00, -5.99179998e-01,  1.61977519e+00,  2.65605178e-02,
       -2.91006191e-01,  3.00632242e-01])

#####  Lets consider 2D array

In [124]:
matrix = np.random.randn(3,4)

In [132]:
matrix

array([[ 1.33637418, -0.08910403, -0.66575793, -1.20948465],
       [ 1.5529136 , -0.17373563, -0.59229101, -1.79333288],
       [-1.10972018,  0.85608818,  0.08344142,  2.6558091 ]])


The `np.round(matrix, decimal)` function in NumPy rounds the elements of an array to a specified number of decimal places. 

The matrix argument is the array to be rounded, and the decimal argument is the number of decimal places to round to

In [129]:
np.round(matrix,2) 

array([[ 1.34, -0.09, -0.67, -1.21],
       [ 1.55, -0.17, -0.59, -1.79],
       [-1.11,  0.86,  0.08,  2.66]])

In [133]:
matrix.dtype
# returns the data type of the elements in an array 

dtype('float64')

##    <span style="font-family: 'Verdana '; color: green  ">  Summary of the Mathematical Functions </span>

So by now, you must have experimented with different functions taught in the course. Consider an array, then the functions are:


`array-10`  = to subtract from elements in the array.
``
`np.sqrt(array)` = to find the square root of elements in the array.

`np.min(array)` = to find the minimum number from the array.

`np.argmin(array)` = to find an index of the minimum number from the array.

`np.log(array)` = to find log values of elements in the array.

`np.sin(array)` = to find sin values of elements in the array.

`np.tan(array)` = to find tan values of elements in the array.

`np.round(array , decimals = 2)` = to round off elements up to two decimals in the array.

# <span style="font-family: 'Verdana '; color: blue "> Indexing and Selection in NumPy Arrays </span>

In [135]:
arr_ = np.arange(1,10)

In [137]:
arr_

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [139]:
arr_[4]

# shows the element present in the 4th index 
#  in Python, indices start at 0 

5

In [142]:
# access multiple indices in an array

arr_[[0,5,6]]

array([1, 6, 7])

In [151]:
arr_[0:5]
#will return the first 5 elements in the array

array([ 1,  2, 12,  4,  5])

In [146]:
# This is because negative indices in Python start at the end of the array, so -1 refers to the last element.

arr_[-1]

9

In [148]:
# change the values using indices
arr_[2] = 12

In [150]:
arr_
# as you can see the value of the 2nd index is changed from 3 to 12 

array([ 1,  2, 12,  4,  5,  6,  7,  8,  9])

In [153]:
arr_[4:7]= 25 
# replace the elements at indices 4, 5, and 6 in the array arr_ with the value 25.
# This is because the colon (:) in Python is used to slice an array, 
# and the range [4:7] refers to the elements at indices 4, 5, and 6 in the array.

In [154]:
arr_

array([ 1,  2, 12,  4, 25, 25, 25,  8,  9])

##### consider 2D array 

In [169]:
arr_2D = np.arange(1,21).reshape(4,5)
arr_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [171]:
arr_2D [:,(2,4)]
# will return the elements at the second and fourth columns of the array arr_2D. 
# This is because the colon (:) in Python is used to slice an array, 
# and the tuple (2,4) refers to the elements at the second and fourth columns of the array.

array([[ 3,  5],
       [ 8, 10],
       [13, 15],
       [18, 20]])

In [172]:
arr_2D[(1,2),(2,4)]

# will return the elements at the row 1 and column 2 and row 2 and column 4 of the array arr_2D. 
# This is because the first tuple (1,2) refers to the elements at row 1 and column 2 of the array, 
# and the second tuple (2,4) refers to the elements at row 2 and column 4 of the array.

array([ 8, 15])

# <span style="font-family: 'Verdana '; color: green  "> Author: Hasan Ali   </span>